### ISSUE TITLE
Unable to build the Claw library on Mac

### ISSUE THREAD

**Issue by Clever-Boy** [j-jorge/pack-my-sprites#5]
[ 62%] Linking CXX shared library libclaw_graphic.dylib
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin17.0.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
 "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld" -demangle -lto_library /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib -dynamic -dylib -dylib_compatibility_version 1.0.0 -dylib_current_version 1.7.4 -arch x86_64 -dylib_install_name /users/mac/Downloads/libclaw-1.7.4/build/libclaw_graphic.1.dylib -headerpad_max_install_names -macosx_version_min 10.12.0 -syslibroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk -s -o libclaw_graphic.1.7.4.dylib -all_load -noall_load CMakeFiles/claw_graphic.dir/claw/code/image.cpp.o CMakeFiles/claw_graphic.dir/claw/code/bitmap.cpp.o CMakeFiles/claw_graphic.dir/claw/code/bitmap_writer.cpp.o CMakeFiles/claw_graphic.dir/claw/code/bitmap_reader.cpp.o CMakeFiles/claw_graphic.dir/claw/code/gif.cpp.o CMakeFiles/claw_graphic.dir/claw/code/gif_frame.cpp.o CMakeFiles/claw_graphic.dir/claw/code/gif_reader.cpp.o CMakeFiles/claw_graphic.dir/claw/code/pcx.cpp.o CMakeFiles/claw_graphic.dir/claw/code/pcx_reader.cpp.o CMakeFiles/claw_graphic.dir/claw/code/pcx_writer.cpp.o CMakeFiles/claw_graphic.dir/claw/code/pixel.cpp.o CMakeFiles/claw_graphic.dir/claw/code/targa.cpp.o CMakeFiles/claw_graphic.dir/claw/code/targa_writer.cpp.o CMakeFiles/claw_graphic.dir/claw/code/targa_reader.cpp.o CMakeFiles/claw_graphic.dir/claw/code/targa_file_structure.cpp.o CMakeFiles/claw_graphic.dir/claw/code/xbm.cpp.o CMakeFiles/claw_graphic.dir/claw/code/xbm_reader.cpp.o CMakeFiles/claw_graphic.dir/claw/code/xbm_writer.cpp.o -lc++ -lSystem /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/8.1.0/lib/darwin/libclang_rt.osx.a
ld: warning: option -s is obsolete and being ignored
Undefined symbols for architecture x86_64:
  "claw::graphic::png::reader::reader(claw::graphic::image&, std::__1::basic_istream<char, std::__1::char_traits<char> >&)", referenced from:
      claw::graphic::image::load(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image.cpp.o
  "claw::graphic::jpeg::reader::reader(claw::graphic::image&, std::__1::basic_istream<char, std::__1::char_traits<char> >&)", referenced from:
      claw::graphic::image::load(std::__1::basic_istream<char, std::__1::char_traits<char> >&) in image.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libclaw_graphic.1.7.4.dylib] Error 1
make[1]: *** [CMakeFiles/claw_graphic.dir/all] Error 2
make: *** [all] Error 2

**Comment by Clever-Boy** [comment]
I went past this error by installing libraries for Jpeg and Png. Now i am getting an error for logger. Not sure if which dependency I need to install. Any help is much appreciated.

[ 86%] Linking CXX shared library libclaw_logger.dylib
ld: warning: option -s is obsolete and being ignored
ld: warning: option -noall_load is obsolete and being ignored
Undefined symbols for architecture x86_64:
  "_libintl_dgettext", referenced from:
      dgettext(char const*, char const*) in log_stream_uniq.cpp.o
      dgettext(char const*, char const*) in log_level.cpp.o
  "_libintl_dngettext", referenced from:
      dngettext(char const*, char const*, char const*, unsigned long) in log_stream_uniq.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libclaw_logger.1.7.4.dylib] Error 1
make[1]: *** [CMakeFiles/claw_logger.dir/all] Error 2

**Comment by j-jorge** [comment]
You need to install the gettext library in order to build libclaw.

**Comment by Clever-Boy** [comment]
I installed gettext and have the following files in usr/local/lib 

libgettextlib-0.18.3.dylib	libgettextpo.dylib
libgettextlib-0.19.8.1.dylib	libgettextpo.la
libgettextlib.dylib		libgettextsrc-0.18.3.dylib
libgettextlib.la		libgettextsrc-0.19.8.1.dylib
libgettextpo.0.dylib		libgettextsrc.dylib
libgettextpo.a			libgettextsrc.la

I tried using make again and it still errors out with above error. Does the CMAKE file need to look for gettext libraries? I am not that good at Cmake. 

Current entries have :

# log system
set( CLAW_LOGGER_SOURCES
  ${CLAW_CODE_DIR}logger.cpp
  ${CLAW_CODE_DIR}log_stream.cpp
  ${CLAW_CODE_DIR}log_stream_concise.cpp
  ${CLAW_CODE_DIR}log_stream_uniq.cpp
  ${CLAW_CODE_DIR}log_level.cpp
)
add_library( claw_logger SHARED ${CLAW_LOGGER_SOURCES} )
add_library( claw_logger-static STATIC ${CLAW_LOGGER_SOURCES} )


For PNG it looks for dependencies

# check png library
if( PNG_FOUND )
  **set( CLAW_GRAPHIC_LIBRARIES ${CLAW_GRAPHIC_LIBRARIES} ${PNG_LIBRARIES} )
  set( CLAW_GRAPHIC_SOURCES ${CLAW_GRAPHIC_SOURCES}**
      ${CLAW_CODE_DIR}png.cpp
      ${CLAW_CODE_DIR}png_reader.cpp
      ${CLAW_CODE_DIR}png_writer.cpp
   )
else( PNG_FOUND )
  message( "png library not found." )
endif( PNG_FOUND )

**Comment by j-jorge** [comment]
My bad, it's the `libintl` library that must be installed to fix these errors. On my system the following libraries are found by CMake :

> Boost_SYSTEM_LIBRARY_DEBUG:FILEPATH=/usr/local/lib/libboost_system-mt.dylib
Boost_SYSTEM_LIBRARY_RELEASE:FILEPATH=/usr/local/lib/libboost_system-mt.dylib
Boost_THREAD_LIBRARY_DEBUG:FILEPATH=/usr/local/lib/libboost_thread-mt.dylib
Boost_THREAD_LIBRARY_RELEASE:FILEPATH=/usr/local/lib/libboost_thread-mt.dylib
INTL_LIBRARY:FILEPATH=/usr/local/lib/libintl.dylib
JPEG_LIBRARY:FILEPATH=/usr/local/lib/libjpeg.dylib
PNG_LIBRARY_RELEASE:FILEPATH=/usr/local/lib/libpng.dylib
ZLIB_LIBRARY_RELEASE:FILEPATH=/usr/lib/libz.dylib

**Comment by Clever-Boy** [comment]
Finally I found the error. The cmake file on the sourceforge link to download claw library is missing the lines for linking boost and finding the INTL library.. (The link is in the INSTALL file for Pack-my-sprites) 

add_library( claw_logger SHARED ${CLAW_LOGGER_SOURCES} )
add_library( claw_logger-static STATIC ${CLAW_LOGGER_SOURCES} )

#-------- New ------
target_link_libraries(
  claw_logger ${Boost_THREAD_LIBRARY} ${Boost_SYSTEM_LIBRARY}
  )

find_library( INTL_LIBRARY intl )

if ( INTL_LIBRARY )
  target_link_libraries(
    claw_logger ${INTL_LIBRARY}
    )
endif( INTL_LIBRARY )
# ---------- END NEW ------

[ 15%] Built target claw_tween-static
[ 17%] Built target claw_dynamic_library-static
[ 20%] Built target claw_application-static
[ 41%] Built target claw_graphic-static
[ 56%] Built target claw_tween
[ 58%] Built target claw_net-static
[ 79%] Built target claw_graphic
[ 81%] Built target claw_dynamic_library
[ 86%] Built target claw_logger
[ 89%] Built target claw_application
[ 90%] Built target claw_configuration_file-static
[ 92%] Built target claw_configuration_file
[ 94%] Built target claw_net
[ 99%] Built target claw_logger-static
[100%] Generating fr.gmo
[100%] Built target libclaw-translations
